#!/bin/sh

get_kbdlayout() { # prints out keyboard layout in xx-variant format.
  q="$(setxkbmap -query)"
  variant="$(echo "$q" | grep -oP 'variant:\s*\K(\w+)')" && variant="-$variant"
  echo "$(echo "$q" | grep -oP 'layout:\s*\K([\w,]+)')$variant"
}

set_kbdlayout() { # accepts either the layout (xx) or layout and variant separated with a dash (xx-variant)
  setxkbmap "$(echo "$1" | cut -d- -f1)" "$(echo "$1" | cut -s -d- -f2)"
  pgrep i3status | xargs --no-run-if-empty kill -s USR1 # tell i3status to update
  # pkill -RTMIN+30 "${STATUSBAR:-dwmblocks}" # for most other statusbars (e.g: i3blocks or dwmblocks)
}

i3status() {
  while :
  do
    read line
    block="{\"full_text\":\"$(get_kbdlayout)\"}"
    # FIXME make bash independent
    echo "${line/\[\{/\[$block,\{}"|| exit 1
  done
}

subcommand="$1"
shift || (echo "Please specify one of: get, set <layout>, cycle <layout1> <layout2> ... <layoutN>, i3status" && exit)

case $subcommand in
  "get")
    get_kbdlayout
    ;;
  "set")
    set_kbdlayout "$1"
    ;;
  "cycle")
    set_kbdlayout "$(echo "$@" | grep -oP ".*$(get_kbdlayout) +\\K[\\w-]+" || echo "$1")"
    ;;
  "i3status")
    i3status
    ;;
esac
